(() => {
  "use strict";

  const VERSION = "5.3.0";
  const LEGACY_STORAGE_KEY = "presencialidad-aulas-v1";
  const PREFS_KEY = "presencialidad-preferences-v5";
  const DRAFT_PREFIX = "presencialidad-v5-draft:";
  const AUTOSAVE_MS = 15000;
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const I18N = window.PresencialidadI18n;
  const t = value => I18N?.translate(value) ?? value;

  const app = {
    user: null,
    classrooms: [],
    students: [],
    selectedClassroomId: null,
    draftAttendance: {},
    attendanceDirty: false,
    currentProfileStudent: null,
    currentReportId: null,
    currentAssessment: null,
    adminUsers: [],
    backendOnline: false,
    importPayload: null,
    searchTimer: null,
    csrf: "",
    google: null,
    setupRequired: false,
    settings: {},
    archivedClassrooms: [],
    institutionName: "",
    editingNoteId: null,
    privateNotes: [],
    currentProfileNotes: [],
  };

  const els = {};
  const ids = [
    "setupShell","setupForm","setupInstitution","setupName","setupEmail","setupAcademicYear","setupLanguage","setupPassword","setupPasswordRepeat","appShell","loginInstitutionName",
    "backendBanner","globalToolbar","globalSearchInput","globalSearchResults","connectionPill","toast","accountMini","signedOutMini","accountInitials","accountMiniName","accountMiniRole",
    "homeDate","todayClassesList","noTodayClasses","alertsList","noAlerts",
    "attendanceDate","classroomGrid","noClassroomsAttendance","classroomSelectorPanel","attendancePanel","attendanceClassroomName","attendanceSubline","attendanceBody","noStudentsAttendance","backToClassrooms","markAllPresent","saveAttendance","attendanceStatus","autosaveStatus","presentCount","absentCount","lateCount","justifiedCount","earlyCount",
    "historyDate","historyClassroom","historyBody","historySummary","noHistory","clearHistoryButton","reportMonth","reportClassroom","exportAttendanceCsv","exportAttendancePdf","exportStudentsCsv","exportStudentsPdf","exportReportsCsv","exportReportsPdf",
    "gradesClassroom","assessmentList","noAssessments","newAssessmentButton",
    "privateNotesSearch","privateNotesClassroom","privateNotesList","noPrivateNotes","refreshPrivateNotesButton",
    "scheduleForm","scheduleKind","scheduleTitle","scheduleClassroom","scheduleDate","scheduleTime","scheduleNote","scheduleRepeat","scheduleList","noSchedule",
    "classroomForm","classroomNameInput","classroomAdminList","studentFilter","studentAdminList","newStudentButton","newUserButton","userAdminList","studentImportFile","previewImportButton","commitImportButton","importPreview","settingsForm","attendanceThreshold",
    "institutionNameSetting","academicYearSetting","educationLevelSetting","shiftsSetting","absenceAlertCount","lateAlertCount","defaultLanguageSetting","autoBackupEnabled","backupIntervalHours","backupKeep","sessionHours","publicBaseUrl","googleClientId","googleClientSecret","createBackupButton","backupList","noBackups","archivedClassroomList","noArchivedClassrooms","inactiveStudentList","noInactiveStudents",
    "loginPanel","loggedAccount","loginForm","loginEmail","loginPassword","forgotPasswordButton","profileInitials","profileAvatarImage","profileName","profileRole","profileEmail","profileInstitution","profileClassrooms","profileLastLogin","logoutButton","accountTabs","myReportsList","noMyReports","activityList","reviewReportsList","changePasswordForm","currentPassword","newPassword","repeatPassword",
    "profileForm","profileNameInput","profileEmailInput","profileLanguageInput","profileAvatarInput","profileUseGooglePicture","googleStatusCard","googleStatusTitle","googleStatusDetail","connectGoogleButton","enableGmailButton","testGmailButton","disconnectGoogleButton","sessionList","revokeOtherSessions",
    "refreshSystemButton","appVersionValue","backendStatusValue","backendModeValue","uptimeValue","requestsValue","dbSizeValue","dbNameValue","dbIntegrityValue","dataDirValue","statUsers","statClassrooms","statStudents","statAttendance","statReports","statNotes","statAssessments","statSchedule","specsHelpButton","specsDialog","specsContent","migrateLocalButton",
    "studentDialog","studentForm","studentDialogTitle","studentIdInput","studentNameInput","studentRecordInput","studentClassroomInput","studentDniInput","studentBirthDateInput","studentGuardianNameInput","studentGuardianPhoneInput","studentGuardianEmailInput","studentEmergencyNameInput","studentEmergencyPhoneInput",
    "studentProfileDialog","profileStudentMeta","profileStudentName","profileInfoTab","profileAttendanceTab","profileReportsTab","profileNotesTab","profileGradesTab","profileNoticesTab","reportStudentButton","privateNoteButton","familyNoticeButton",
    "reportDialog","reportForm","reportStudentName","reportStudentClass","reportDate","reportType","reportDescription","reportPriority",
    "followupDialog","followupForm","followupList","followupComment","noteDialog","noteForm","noteDialogTitle","privateNoteText","noticeDialog","noticeForm","noticeReason","noticeMessage","noticeMarkSent","noticeSendGmail",
    "assessmentDialog","assessmentForm","assessmentClassroom","assessmentTitle","assessmentDate","assessmentMaxScore","gradesDialog","gradesForm","gradesDialogTitle","gradesBody","saveGradesButton",
    "userDialog","userForm","userDialogTitle","userIdInput","userNameInput","userEmailInput","userRoleInput","userInstitutionInput","userPasswordInput","initialPasswordField","userClassroomChecks","userActiveLabel","userActiveInput","resetUserPasswordButton",
    "confirmClearDialog","confirmClearInput","confirmClearAction"
  ];
  ids.forEach(id => els[id] = document.getElementById(id));
  els.navButtons = $$(".nav-button");
  els.views = $$(".view");
  els.adminOnly = $$(".admin-only");
  els.reviewOnly = $$(".review-only");
  els.editGradesOnly = $$(".edit-grades-only");

  function today() {
    const d = new Date();
    return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
  }
  function monthNow() { return today().slice(0, 7); }
  function esc(value) { return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
  function initials(name) { return String(name || "?").replace(/^Profesor\s+/i,"").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase() || "?"; }
  function roleLabel(role) { return I18N?.role(role) ?? role; }
  function statusText(status) { return I18N?.status(status) ?? status; }
  function reportTypeText(type) { return I18N?.reportType(type) ?? type; }
  function priorityText(priority) { return I18N?.priority(priority) ?? priority; }
  function formatDate(iso) {
    if (!iso) return "—";
    const d = new Date(`${String(iso).slice(0,10)}T00:00:00Z`);
    return Number.isNaN(d.getTime()) ? iso : new Intl.DateTimeFormat(I18N?.locale() || "es-AR", {dateStyle:"medium",timeZone:"UTC"}).format(d);
  }
  function formatDateTime(value) {
    if (!value) return "—";
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat(I18N?.locale() || "es-AR", {dateStyle:"short",timeStyle:"short"}).format(d);
  }
  function formatBytes(bytes) {
    const n=Number(bytes); if(!Number.isFinite(n)) return "—"; if(n<1024)return `${n} B`; if(n<1048576)return `${(n/1024).toFixed(1)} KB`; return `${(n/1048576).toFixed(1)} MB`;
  }
  function formatDuration(seconds) {
    const s=Math.max(0,Math.floor(Number(seconds)||0)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;
    return h?`${h} h ${m} min`:m?`${m} min ${r} s`:`${r} s`;
  }
  function toast(message) {
    els.toast.textContent=t(message); els.toast.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>els.toast.classList.remove("show"),2800);
  }

  async function api(path, options={}) {
    const opts={credentials:"same-origin",...options,headers:{...(options.headers||{})}};
    const method=String(opts.method||"GET").toUpperCase();
    if(app.csrf && !["GET","HEAD","OPTIONS"].includes(method)) opts.headers["X-CSRF-Token"]=app.csrf;
    if (opts.body && typeof opts.body !== "string") { opts.headers["Content-Type"]="application/json"; opts.body=JSON.stringify(opts.body); }
    let response;
    try { response=await fetch(path,opts); setConnection(true); }
    catch (error) { setConnection(false); throw error; }
    let data={}; try{data=await response.json();}catch(_){}
    if(!response.ok){const e=new Error(data.error||`Error ${response.status}`);e.status=response.status;e.data=data;throw e;}
    return data;
  }

  async function downloadApi(path) {
    let response;
    try { response=await fetch(path); setConnection(true); } catch(e) { setConnection(false); throw e; }
    if(!response.ok){let d={};try{d=await response.json();}catch(_){};throw new Error(d.error||`Error ${response.status}`);}
    const blob=await response.blob();
    const disposition=response.headers.get("Content-Disposition")||"";
    const match=disposition.match(/filename\*=UTF-8''([^;]+)/i); const filename=match?decodeURIComponent(match[1]):"exportacion";
    const url=URL.createObjectURL(blob); const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);
  }

  function setConnection(online) {
    app.backendOnline=online;
    els.backendBanner?.classList.toggle("hidden",online);
    if(els.connectionPill){els.connectionPill.classList.toggle("offline",!online);els.connectionPill.querySelector("strong").textContent=t(online?"Conectado":"Sin conexión");}
  }

  function sanitizeDigits(value){return String(value||"").replace(/\D+/g,"").slice(0,9);}
  function sanitizePhone(value){return String(value||"").replace(/[^0-9+() .-]+/g,"").slice(0,30);}
  function bindRestrictedInputs(){
    [els.studentDniInput].forEach(input=>{if(!input)return;input.addEventListener("beforeinput",e=>{if(e.inputType==="insertText"&&e.data&&/\D/.test(e.data))e.preventDefault();});input.addEventListener("input",()=>input.value=sanitizeDigits(input.value));});
    [els.studentGuardianPhoneInput,els.studentEmergencyPhoneInput].forEach(input=>{if(!input)return;input.addEventListener("beforeinput",e=>{if(e.inputType==="insertText"&&e.data&&/[^0-9+() .-]/.test(e.data))e.preventDefault();});input.addEventListener("input",()=>input.value=sanitizePhone(input.value));});
  }

  function applyAppearance(){let prefs={theme:"light",accent:"turquoise"};try{prefs={...prefs,...JSON.parse(localStorage.getItem(PREFS_KEY)||localStorage.getItem("presencialidad-preferences-v4")||localStorage.getItem("presencialidad-preferences-v311")||"{}")};}catch(_){}document.documentElement.dataset.theme=prefs.theme;document.documentElement.dataset.accent=prefs.accent;$$('[data-theme-choice]').forEach(b=>b.classList.toggle("active",b.dataset.themeChoice===prefs.theme));$$('.color-choice').forEach(b=>b.classList.toggle("active",b.dataset.accent===prefs.accent));}
  function saveAppearance(next){let prefs={};try{prefs=JSON.parse(localStorage.getItem(PREFS_KEY)||"{}");}catch(_){}localStorage.setItem(PREFS_KEY,JSON.stringify({...prefs,...next}));applyAppearance();}

  function switchView(viewId){
    const button=els.navButtons.find(b=>b.dataset.view===viewId);if(button?.classList.contains("locked")||button?.classList.contains("hidden"))return;
    els.views.forEach(v=>v.classList.toggle("active",v.id===viewId));els.navButtons.forEach(b=>b.classList.toggle("active",b.dataset.view===viewId));
    if(!app.user && !["accountView","appearanceView","systemView"].includes(viewId)) return switchView("accountView");
    if(viewId==="homeView")renderHome(); if(viewId==="historyView")renderHistory(); if(viewId==="gradesView")renderGradesView(); if(viewId==="calendarView")renderCalendar(); if(viewId==="notesView")renderPrivateNotes(); if(viewId==="adminView"&&app.user?.permissions.admin)renderAdmin(); if(viewId==="accountView"&&app.user)renderAccountData(); if(viewId==="systemView")refreshSystem();
  }

  function updateAuthUI(){
    const signed=!!app.user;els.loginPanel?.classList.toggle("hidden",signed);els.loggedAccount?.classList.toggle("hidden",!signed);els.accountMini?.classList.toggle("hidden",!signed);els.signedOutMini?.classList.toggle("hidden",signed);els.globalToolbar?.classList.toggle("hidden",!signed);
    els.navButtons.forEach(btn=>{if(!["accountView","appearanceView","systemView"].includes(btn.dataset.view))btn.classList.toggle("locked",!signed);});
    els.adminOnly.forEach(el=>el.classList.toggle("hidden",!app.user?.permissions?.admin));els.reviewOnly.forEach(el=>el.classList.toggle("hidden",!app.user?.permissions?.review_reports));els.editGradesOnly.forEach(el=>el.classList.toggle("hidden",!app.user?.permissions?.edit_grades));
    if(!signed){app.classrooms=[];app.google=null;renderClassroomCards();return;}
    const u=app.user;els.accountInitials.textContent=initials(u.name);els.accountMiniName.textContent=u.name;els.accountMiniRole.textContent=roleLabel(u.role);els.profileInitials.textContent=initials(u.name);els.profileName.textContent=u.name;els.profileRole.textContent=roleLabel(u.role);els.profileEmail.textContent=u.email;els.profileInstitution.textContent=u.institution||"—";els.profileClassrooms.textContent=u.classrooms?.length?u.classrooms.map(c=>c.name).join(", "):(u.permissions.admin?t("Todas"):t("Sin aulas asignadas"));els.profileLastLogin.textContent=formatDateTime(u.last_login);
    if(els.profileAvatarImage){const avatar=u.avatar_url||"";els.profileAvatarImage.classList.toggle("hidden",!avatar);els.profileInitials.classList.toggle("hidden",!!avatar);if(avatar)els.profileAvatarImage.src=avatar;}
    if(els.profileNameInput)els.profileNameInput.value=u.name||"";if(els.profileEmailInput)els.profileEmailInput.value=u.email||"";if(els.profileLanguageInput)els.profileLanguageInput.value=u.preferred_language||I18N?.language?.()||"es";if(els.profileAvatarInput)els.profileAvatarInput.value=u.avatar_url||"";
  }

  function applyInstitutionBrand(name){
    app.institutionName=String(name||"").trim();
    if(els.loginInstitutionName)els.loginInstitutionName.textContent=app.institutionName||"Presencialidad";
    document.title=app.institutionName?`${app.institutionName} · Presencialidad ${VERSION}`:`Presencialidad | ${VERSION}`;
  }
  async function checkSetup(){
    try{const data=await api("/api/setup/status");app.setupRequired=!!data.needs_setup;applyInstitutionBrand(data.institution||"");if(els.setupShell)els.setupShell.classList.toggle("hidden",!app.setupRequired);if(els.appShell)els.appShell.classList.toggle("hidden",app.setupRequired);if(app.setupRequired){els.setupAcademicYear.value=String(new Date().getFullYear());els.setupLanguage.value=I18N?.language?.()||"es";return true;}return false;}catch(_){setConnection(false);return false;}
  }
  async function completeSetup(e){
    e.preventDefault();if(els.setupPassword.value!==els.setupPasswordRepeat.value)return toast("Las contraseñas no coinciden.");
    try{const data=await api("/api/setup",{method:"POST",body:{institution_name:els.setupInstitution.value,name:els.setupName.value,email:els.setupEmail.value,academic_year:els.setupAcademicYear.value,language:els.setupLanguage.value,password:els.setupPassword.value}});app.user=data.user;app.csrf=data.csrf_token||"";app.setupRequired=false;applyInstitutionBrand(els.setupInstitution.value);els.setupShell.classList.add("hidden");els.appShell.classList.remove("hidden");if(data.user?.preferred_language)I18N?.setLanguage?.(data.user.preferred_language);await loadClassrooms();updateAuthUI();renderClassroomCards();toast("Configuración inicial completada.");switchView("homeView");}catch(err){toast(err.message);}
  }
  async function checkBackendAndSession(){
    try{await api("/api/status");}catch(_){app.user=null;app.csrf="";updateAuthUI();switchView("accountView");return;}
    if(await checkSetup())return;
    try{const data=await api("/api/auth/me");app.user=data.user;app.csrf=data.csrf_token||"";app.google=data.google||null;if(app.user?.preferred_language&&I18N?.language?.()!==app.user.preferred_language)I18N?.setLanguage?.(app.user.preferred_language);await loadClassrooms();updateAuthUI();renderClassroomCards();switchView("homeView");syncPendingDrafts();}catch(e){if(e.status!==401)console.error(e);app.user=null;app.csrf="";app.google=null;updateAuthUI();switchView("accountView");}
  }
  async function loadClassrooms(){if(!app.user){app.classrooms=[];return;}const data=await api("/api/classrooms");app.classrooms=data.classrooms||[];populateClassroomSelects();}
  function populateClassroomSelects(){
    const options=app.classrooms.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("");
    [els.studentClassroomInput,els.assessmentClassroom].forEach(s=>{if(s)s.innerHTML=options;});
    if(els.scheduleClassroom)els.scheduleClassroom.innerHTML=`<option value="">${esc(t("Sin aula"))}</option>${options}`;
    if(els.gradesClassroom)els.gradesClassroom.innerHTML=app.classrooms.length?options:`<option value="">${esc(t("Sin aulas asignadas"))}</option>`;
    if(els.historyClassroom)els.historyClassroom.innerHTML=`<option value="all">${esc(t("Todas mis aulas"))}</option>${options}`;
    if(els.reportClassroom)els.reportClassroom.innerHTML=`<option value="all">${esc(t("Todas mis aulas"))}</option>${options}`;
  }

  async function renderHome(){
    if(!app.user)return;els.homeDate.textContent=formatDate(today());
    try{
      const [schedule,alerts]=await Promise.all([api(`/api/schedule/today?date=${today()}`),api("/api/alerts")]);
      const items=schedule.items||[];els.todayClassesList.innerHTML=items.map(item=>`<article class="today-class-card"><div class="time-badge">${esc(item.start_time||"—")}</div><div><strong data-i18n-skip>${esc(item.title)}</strong><span>${esc(item.classroom_name||t("Sin aula"))} · ${esc(scheduleKindText(item.kind))}</span></div>${item.kind==="class"&&item.classroom_id?`<button class="primary-button today-attendance" data-class="${esc(item.classroom_id)}">${esc(t("Pasar lista"))}</button>`:""}</article>`).join("");els.noTodayClasses.classList.toggle("hidden",items.length>0);$$('.today-attendance').forEach(b=>b.addEventListener("click",async()=>{switchView("attendanceView");await openClassroom(b.dataset.class);}));
      const rows=alerts.alerts||[];els.alertsList.innerHTML=rows.map(a=>`<button class="alert-card" data-student="${esc(a.student_id)}"><strong data-i18n-skip>${esc(a.student_name)}</strong><span>${esc(a.classroom_name)} · ${esc(alertText(a))}</span></button>`).join("");els.noAlerts.classList.toggle("hidden",rows.length>0);$$('.alert-card').forEach(b=>b.addEventListener("click",()=>openStudentProfile(b.dataset.student)));
    }catch(e){toast(e.message);}
  }
  function alertText(a){if(a.type==="consecutive_absences")return t(`${a.value} ausencias consecutivas`);if(a.type==="monthly_lates")return t(`${a.value} llegadas tarde este mes`);if(a.type==="low_attendance")return `${t("Asistencia baja")}: ${a.value}% (< ${a.threshold}%)`;return a.type;}
  function scheduleKindText(k){return t({class:"Clase",assessment:"Evaluación",meeting:"Reunión",reminder:"Recordatorio"}[k]||k);}

  function renderClassroomCards(){els.classroomGrid.innerHTML="";const rows=app.classrooms||[];els.noClassroomsAttendance.classList.toggle("hidden",rows.length>0);rows.forEach(c=>{const b=document.createElement("button");b.className="classroom-card";b.innerHTML=`<strong data-i18n-skip>${esc(c.name)}</strong><span>${c.student_count??0} ${t((c.student_count??0)===1?"alumno":"alumnos")}</span>`;b.addEventListener("click",()=>openClassroom(c.id));els.classroomGrid.appendChild(b);});}

  function localDraftKey(date,classroomId){return `${DRAFT_PREFIX}${app.user?.id||"anon"}:${date}:${classroomId}`;}
  function draftRecords(){return app.students.map(s=>({student_id:s.id,status:app.draftAttendance[s.id]?.status||"",reason:app.draftAttendance[s.id]?.reason||"",arrival_time:app.draftAttendance[s.id]?.arrival_time||"",departure_time:app.draftAttendance[s.id]?.departure_time||""}));}
  function persistLocalDraft(){if(!app.user||!app.selectedClassroomId)return;const payload={date:els.attendanceDate.value,classroom_id:app.selectedClassroomId,records:draftRecords(),updated_at:new Date().toISOString()};localStorage.setItem(localDraftKey(payload.date,payload.classroom_id),JSON.stringify(payload));return payload;}
  function loadLocalDraft(date,classroomId){try{return JSON.parse(localStorage.getItem(localDraftKey(date,classroomId))||"null");}catch(_){return null;}}
  function clearLocalDraft(date,classroomId){localStorage.removeItem(localDraftKey(date,classroomId));}
  function recordsToDraft(records){const out={};(records||[]).forEach(r=>out[r.student_id]={status:r.status||"",reason:r.reason||"",arrival_time:r.arrival_time||"",departure_time:r.departure_time||""});return out;}

  async function openClassroom(classroomId){
    try{
      app.selectedClassroomId=classroomId;const date=els.attendanceDate.value;
      const [studentsData,attendanceData,draftData]=await Promise.all([api(`/api/students?classroom_id=${encodeURIComponent(classroomId)}`),api(`/api/attendance?date=${encodeURIComponent(date)}&classroom_id=${encodeURIComponent(classroomId)}`),api(`/api/attendance/draft?date=${encodeURIComponent(date)}&classroom_id=${encodeURIComponent(classroomId)}`).catch(()=>({draft:null,updated_at:null}))]);
      app.students=studentsData.students||[];app.draftAttendance=recordsToDraft(attendanceData.attendance||[]);let recovered=false;
      const local=loadLocalDraft(date,classroomId);const backendDraft=draftData.draft?{...draftData.draft,updated_at:draftData.updated_at}:null;
      const candidates=[local,backendDraft].filter(Boolean).sort((a,b)=>String(a.updated_at||"").localeCompare(String(b.updated_at||"")));
      if(candidates.length){const latest=candidates[candidates.length-1];if(Array.isArray(latest.records)){app.draftAttendance={...app.draftAttendance,...recordsToDraft(latest.records)};recovered=true;}}
      els.classroomSelectorPanel.classList.add("hidden");els.attendancePanel.classList.remove("hidden");setAttendanceDirty(recovered);renderAttendance();if(recovered)els.autosaveStatus.textContent=t("Borrador recuperado");
    }catch(e){toast(e.message);}
  }
  function closeClassroom(){if(app.attendanceDirty)persistLocalDraft();app.selectedClassroomId=null;app.students=[];app.draftAttendance={};app.attendanceDirty=false;els.attendancePanel.classList.add("hidden");els.classroomSelectorPanel.classList.remove("hidden");}
  function setAttendanceDirty(value){app.attendanceDirty=!!value;els.attendanceStatus.textContent=t(value?"Hay cambios sin guardar":"Sin cambios");}
  function statusCell(studentId,status,selected){return `<td><button class="status-option ${selected===status?"selected":""}" data-student-id="${esc(studentId)}" data-status="${status}" aria-label="${esc(statusText(status))}"></button></td>`;}
  function detailRow(student){
    const d=app.draftAttendance[student.id]||{};const status=d.status||"";if(!["absent","justified","late","early_departure"].includes(status))return "";
    let controls="";
    if(["absent","justified","early_departure"].includes(status))controls+=`<label class="attendance-detail-field"><span>${esc(t("Motivo"))}</span><select class="attendance-reason" data-student-id="${esc(student.id)}"><option value="">${esc(t("Sin motivo cargado"))}</option>${["Enfermedad","Familiar","Actividad institucional","Transporte","Otro"].map(x=>`<option ${d.reason===x?"selected":""}>${esc(t(x))}</option>`).join("")}</select></label>`;
    if(status==="late")controls+=`<label class="attendance-detail-field"><span>${esc(t("Hora de llegada"))}</span><input class="attendance-arrival" data-student-id="${esc(student.id)}" type="time" value="${esc(d.arrival_time||"")}"></label>`;
    if(status==="early_departure")controls+=`<label class="attendance-detail-field"><span>${esc(t("Hora de retiro"))}</span><input class="attendance-departure" data-student-id="${esc(student.id)}" type="time" value="${esc(d.departure_time||"")}"></label>`;
    return `<tr class="attendance-detail-row"><td colspan="6"><div class="attendance-details">${controls}</div></td></tr>`;
  }
  function renderAttendance(){
    const classroom=app.classrooms.find(c=>c.id===app.selectedClassroomId);if(!classroom)return closeClassroom();els.attendanceClassroomName.textContent=classroom.name;els.attendanceSubline.textContent=`${app.students.length} ${t(app.students.length===1?"alumno":"alumnos")} · ${formatDate(els.attendanceDate.value)}`;els.attendanceBody.innerHTML="";els.noStudentsAttendance.classList.toggle("hidden",app.students.length>0);els.saveAttendance.disabled=!app.students.length;
    app.students.forEach(s=>{const d=app.draftAttendance[s.id]||{},selected=d.status||"";const tr=document.createElement("tr");tr.innerHTML=`<td><button class="student-link" data-student="${esc(s.id)}"><strong data-i18n-skip>${esc(s.name)}</strong><small>Legajo ${esc(s.record_number)}</small></button></td>${statusCell(s.id,"present",selected)}${statusCell(s.id,"absent",selected)}${statusCell(s.id,"late",selected)}${statusCell(s.id,"justified",selected)}${statusCell(s.id,"early_departure",selected)}`;els.attendanceBody.appendChild(tr);const details=detailRow(s);if(details)els.attendanceBody.insertAdjacentHTML("beforeend",details);});
    $$('#attendanceBody .status-option').forEach(btn=>btn.addEventListener("click",()=>{const id=btn.dataset.studentId,status=btn.dataset.status,prev=app.draftAttendance[id]||{};app.draftAttendance[id]={status,reason:["absent","justified","early_departure"].includes(status)?prev.reason||"":"",arrival_time:status==="late"?prev.arrival_time||"":"",departure_time:status==="early_departure"?prev.departure_time||"":""};setAttendanceDirty(true);persistLocalDraft();renderAttendance();}));
    $$('#attendanceBody .student-link').forEach(b=>b.addEventListener("click",()=>openStudentProfile(b.dataset.student)));
    $$('#attendanceBody .attendance-reason').forEach(el=>el.addEventListener("change",()=>{app.draftAttendance[el.dataset.studentId].reason=el.value;setAttendanceDirty(true);persistLocalDraft();}));
    $$('#attendanceBody .attendance-arrival').forEach(el=>el.addEventListener("change",()=>{app.draftAttendance[el.dataset.studentId].arrival_time=el.value;setAttendanceDirty(true);persistLocalDraft();}));
    $$('#attendanceBody .attendance-departure').forEach(el=>el.addEventListener("change",()=>{app.draftAttendance[el.dataset.studentId].departure_time=el.value;setAttendanceDirty(true);persistLocalDraft();}));
    updateSummary();
  }
  function updateSummary(){const c={present:0,absent:0,late:0,justified:0,early_departure:0};Object.values(app.draftAttendance).forEach(d=>{if(d?.status in c)c[d.status]++;});els.presentCount.textContent=c.present;els.absentCount.textContent=c.absent;els.lateCount.textContent=c.late;els.justifiedCount.textContent=c.justified;els.earlyCount.textContent=c.early_departure;}
  function markAllPresent(){app.students.forEach(s=>app.draftAttendance[s.id]={status:"present",reason:"",arrival_time:"",departure_time:""});setAttendanceDirty(true);persistLocalDraft();renderAttendance();}
  async function autosaveAttendanceDraft(){
    if(!app.attendanceDirty||!app.selectedClassroomId||!app.user)return;const payload=persistLocalDraft();
    try{const result=await api("/api/attendance/draft",{method:"POST",body:payload});els.autosaveStatus.textContent=`${t("Borrador guardado")} · ${formatDateTime(result.updated_at)}`;}catch(_){els.autosaveStatus.textContent=t("Borrador local · sin conexión");}
  }
  async function saveAttendance(){
    const missing=app.students.filter(s=>!app.draftAttendance[s.id]?.status);if(missing.length)return toast(`${t("Faltan marcar")} ${missing.length} ${t(missing.length===1?"alumno":"alumnos")}.`);
    const payload={date:els.attendanceDate.value,classroom_id:app.selectedClassroomId,records:draftRecords()};
    try{const result=await api("/api/attendance/save",{method:"POST",body:payload});clearLocalDraft(payload.date,payload.classroom_id);setAttendanceDirty(false);els.autosaveStatus.textContent=`${t("Guardado")} · ${formatDateTime(result.saved_at)}`;toast("Asistencia guardada.");await renderHome();}
    catch(e){persistLocalDraft();els.autosaveStatus.textContent=t("Borrador local · sin conexión");toast(e.message||"No se pudo guardar en el servidor. El borrador quedó local.");}
  }
  async function syncPendingDrafts(){if(!app.user||!app.backendOnline)return;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith(`${DRAFT_PREFIX}${app.user.id}:`))continue;try{const payload=JSON.parse(localStorage.getItem(key));await api("/api/attendance/draft",{method:"POST",body:payload});}catch(_){}}}

  function attendanceDetailText(r){const parts=[];if(r.reason)parts.push(t(r.reason));if(r.arrival_time)parts.push(`${t("Llegada")}: ${r.arrival_time}`);if(r.departure_time)parts.push(`${t("Retiro")}: ${r.departure_time}`);return parts.join(" · ")||"—";}
  async function renderHistory(){
    if(!app.user)return;populateClassroomSelects();try{const data=await api(`/api/history?date=${encodeURIComponent(els.historyDate.value)}&classroom_id=${encodeURIComponent(els.historyClassroom.value||"all")}`);const rows=data.attendance||[];els.historyBody.innerHTML=rows.map(r=>`<tr><td><button class="student-link history-student" data-student="${esc(r.student_id)}" data-i18n-skip>${esc(r.student_name)}</button></td><td data-i18n-skip>${esc(r.classroom_name)}</td><td><span class="status-badge ${esc(r.status)}">${esc(statusText(r.status))}</span></td><td>${esc(attendanceDetailText(r))}</td><td data-i18n-skip>${esc(r.updated_by_name)}</td></tr>`).join("");els.noHistory.classList.toggle("hidden",rows.length>0);const counts={};rows.forEach(r=>counts[r.status]=(counts[r.status]||0)+1);els.historySummary.innerHTML=Object.entries(counts).map(([s,n])=>`<span class="history-chip">${n} ${esc(statusText(s))}</span>`).join("");$$('.history-student').forEach(b=>b.addEventListener("click",()=>openStudentProfile(b.dataset.student)));}catch(e){toast(e.message);}
  }

  async function renderGradesView(){
    if(!app.user)return;populateClassroomSelects();if(!app.classrooms.length){els.assessmentList.innerHTML="";els.noAssessments.classList.remove("hidden");return;}if(!els.gradesClassroom.value)els.gradesClassroom.value=app.classrooms[0].id;await loadAssessments();
  }
  async function loadAssessments(){const cid=els.gradesClassroom.value;if(!cid)return;try{const data=await api(`/api/assessments?classroom_id=${encodeURIComponent(cid)}`);const rows=data.assessments||[];els.assessmentList.innerHTML=rows.map(a=>`<article class="assessment-card"><div><strong data-i18n-skip>${esc(a.title)}</strong><span>${formatDate(a.assessment_date)} · ${t("Máximo")} ${a.max_score}</span><small>${a.graded_count||0} ${t("calificados")}</small></div><button class="secondary-button open-grades" data-id="${esc(a.id)}">${esc(t("Abrir"))}</button></article>`).join("");els.noAssessments.classList.toggle("hidden",rows.length>0);$$('.open-grades').forEach(b=>b.addEventListener("click",()=>openGradesDialog(b.dataset.id)));}catch(e){toast(e.message);}}
  function openAssessmentDialog(){if(!app.classrooms.length)return toast("No hay aulas asignadas.");populateClassroomSelects();els.assessmentForm.reset();els.assessmentClassroom.value=els.gradesClassroom.value||app.classrooms[0].id;els.assessmentDate.value=today();els.assessmentMaxScore.value="10";els.assessmentDialog.showModal();}
  async function createAssessment(e){e.preventDefault();try{await api("/api/assessments",{method:"POST",body:{classroom_id:els.assessmentClassroom.value,title:els.assessmentTitle.value,assessment_date:els.assessmentDate.value,max_score:els.assessmentMaxScore.value}});els.assessmentDialog.close();toast("Evaluación creada.");els.gradesClassroom.value=els.assessmentClassroom.value;await loadAssessments();}catch(err){toast(err.message);}}
  async function openGradesDialog(id){try{const data=await api(`/api/assessments/${encodeURIComponent(id)}/grades`);app.currentAssessment=data.assessment;els.gradesDialogTitle.textContent=`${data.assessment.title} · ${data.assessment.classroom_name}`;els.gradesBody.innerHTML=(data.students||[]).map(s=>`<tr><td><strong data-i18n-skip>${esc(s.name)}</strong><small>Legajo ${esc(s.record_number)}</small></td><td><input class="grade-score" data-student="${esc(s.id)}" type="number" min="0" max="${esc(data.assessment.max_score)}" step="0.1" value="${s.score??""}" ${data.can_edit?"":"disabled"}></td><td><input class="grade-comment" data-student="${esc(s.id)}" value="${esc(s.comment||"")}" ${data.can_edit?"":"disabled"}></td></tr>`).join("");els.saveGradesButton.classList.toggle("hidden",!data.can_edit);els.gradesDialog.showModal();}catch(e){toast(e.message);}}
  async function saveGrades(e){e.preventDefault();if(!app.currentAssessment)return;const records=$$('.grade-score').map(input=>({student_id:input.dataset.student,score:input.value,comment:document.querySelector(`.grade-comment[data-student="${CSS.escape(input.dataset.student)}"]`)?.value||""}));try{await api(`/api/assessments/${encodeURIComponent(app.currentAssessment.id)}/grades`,{method:"POST",body:{records}});toast("Calificaciones guardadas.");els.gradesDialog.close();await loadAssessments();}catch(err){toast(err.message);}}

  async function renderCalendar(){if(!app.user)return;populateClassroomSelects();els.scheduleDate.value=els.scheduleDate.value||today();try{const data=await api("/api/schedule");const rows=data.items||[];els.scheduleList.innerHTML=rows.map(i=>`<article class="schedule-card"><div><span class="kind-pill">${esc(scheduleKindText(i.kind))}</span><strong data-i18n-skip>${esc(i.title)}</strong><span>${formatDate(i.event_date)}${i.start_time?` · ${esc(i.start_time)}`:""}${i.classroom_name?` · ${esc(i.classroom_name)}`:""}</span>${i.note?`<small data-i18n-skip>${esc(i.note)}</small>`:""}${i.repeat_weekly?`<small>${esc(t("Repite semanalmente"))}</small>`:""}</div><button class="icon-button delete-schedule" data-id="${esc(i.id)}" title="${esc(t("Eliminar"))}">×</button></article>`).join("");els.noSchedule.classList.toggle("hidden",rows.length>0);$$('.delete-schedule').forEach(b=>b.addEventListener("click",()=>deleteSchedule(b.dataset.id)));}catch(e){toast(e.message);}}
  async function createSchedule(e){e.preventDefault();try{await api("/api/schedule",{method:"POST",body:{kind:els.scheduleKind.value,title:els.scheduleTitle.value,classroom_id:els.scheduleClassroom.value,event_date:els.scheduleDate.value,start_time:els.scheduleTime.value,note:els.scheduleNote.value,repeat_weekly:els.scheduleRepeat.checked}});els.scheduleForm.reset();els.scheduleDate.value=today();toast("Evento guardado.");await renderCalendar();await renderHome();}catch(err){toast(err.message);}}
  async function deleteSchedule(id){if(!confirm(t("¿Eliminar este evento?")))return;try{await api(`/api/schedule/${encodeURIComponent(id)}`,{method:"DELETE"});await renderCalendar();await renderHome();}catch(e){toast(e.message);}}

  async function renderAdmin(){
    if(!app.user?.permissions.admin)return;try{const [studentsData,allStudentsData,usersData,settingsData,allClasses]=await Promise.all([api("/api/students"),api("/api/students?include_inactive=1"),api("/api/admin/users"),api("/api/settings"),api("/api/classrooms?include_archived=1")]);app.students=studentsData.students||[];app.inactiveStudents=(allStudentsData.students||[]).filter(s=>!s.active);app.adminUsers=usersData.users||[];app.settings=settingsData||{};app.archivedClassrooms=(allClasses.classrooms||[]).filter(c=>!!c.archived);fillSettings();renderClassroomAdmin();renderArchivedClassrooms();renderInactiveStudents();renderStudentAdmin();renderUserAdmin();populateClassroomSelects();await loadBackups();}catch(e){toast(e.message);}
  }
  function fillSettings(){const x=app.settings||{};els.institutionNameSetting.value=x.institution_name||"";els.academicYearSetting.value=x.academic_year||new Date().getFullYear();els.educationLevelSetting.value=x.education_level||"";els.shiftsSetting.value=x.shifts||"";els.attendanceThreshold.value=x.attendance_threshold??75;els.absenceAlertCount.value=x.absence_alert_count??3;els.lateAlertCount.value=x.late_alert_count??5;els.defaultLanguageSetting.value=x.default_language||"es";els.autoBackupEnabled.checked=x.auto_backup_enabled!==false;els.backupIntervalHours.value=x.backup_interval_hours??24;els.backupKeep.value=x.backup_keep??30;els.sessionHours.value=x.session_hours??8;els.publicBaseUrl.value=x.public_base_url||"";els.googleClientId.value=x.google_client_id||"";els.googleClientSecret.value="";}
  function renderArchivedClassrooms(){const rows=app.archivedClassrooms||[];els.archivedClassroomList.innerHTML=rows.map(c=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(c.name)}</strong><small>${c.student_count||0} ${esc(t("alumnos"))}</small></div><button class="secondary-button restore-classroom" data-id="${esc(c.id)}">${esc(t("Restaurar"))}</button></div>`).join("");els.noArchivedClassrooms.classList.toggle("hidden",rows.length>0);$$('.restore-classroom').forEach(b=>b.addEventListener("click",()=>restoreClassroom(b.dataset.id)));}
  async function restoreClassroom(id){try{await api(`/api/classrooms/${encodeURIComponent(id)}`,{method:"PATCH",body:{archived:false}});toast("Aula restaurada.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(e){toast(e.message);}}
  function renderInactiveStudents(){const rows=app.inactiveStudents||[];els.inactiveStudentList.innerHTML=rows.map(s=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(s.name)}</strong><small>Legajo ${esc(s.record_number)} · ${esc(s.classroom_name)}</small></div><button class="secondary-button restore-student" data-id="${esc(s.id)}">${esc(t("Restaurar"))}</button></div>`).join("");els.noInactiveStudents.classList.toggle("hidden",rows.length>0);$$('.restore-student').forEach(b=>b.addEventListener("click",()=>restoreStudent(b.dataset.id)));}
  async function restoreStudent(id){try{await api(`/api/students/${encodeURIComponent(id)}/restore`,{method:"POST",body:{}});toast("Alumno restaurado.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(e){toast(e.message);}}
  async function loadBackups(){try{const data=await api("/api/backups");const rows=data.backups||[];els.backupList.innerHTML=rows.map(b=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(b.name)}</strong><small>${formatBytes(b.bytes)} · ${formatDateTime(b.modified_at)}</small></div><div class="row-actions"><button class="secondary-button download-backup" data-name="${esc(b.name)}">${esc(t("Descargar"))}</button><button class="danger-button restore-backup" data-name="${esc(b.name)}">${esc(t("Restaurar"))}</button></div></div>`).join("");els.noBackups.classList.toggle("hidden",rows.length>0);$$('.download-backup').forEach(b=>b.addEventListener("click",()=>downloadApi(`/api/backups/download?name=${encodeURIComponent(b.dataset.name)}`)));$$('.restore-backup').forEach(b=>b.addEventListener("click",()=>restoreBackup(b.dataset.name)));}catch(e){toast(e.message);}}
  async function createBackup(){try{await api("/api/backups",{method:"POST",body:{}});toast("Copia de seguridad creada.");await loadBackups();}catch(e){toast(e.message);}}
  async function restoreBackup(name){const confirmText=prompt(t("Escribí RESTAURAR para confirmar. Se creará una copia de seguridad del estado actual."),"");if(confirmText!=="RESTAURAR")return;try{await api("/api/backups/restore",{method:"POST",body:{name,confirm:"RESTAURAR"}});alert(t("Copia restaurada. La sesión se cerrará para volver a cargar los datos."));location.reload();}catch(e){toast(e.message);}}

  function renderClassroomAdmin(){els.classroomAdminList.innerHTML=app.classrooms.map(c=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(c.name)}</strong><small>${c.student_count??0} ${t((c.student_count??0)===1?"alumno":"alumnos")}</small></div><div class="row-actions"><button class="secondary-button rename-classroom" data-id="${esc(c.id)}">${esc(t("Renombrar"))}</button><button class="danger-button delete-classroom" data-id="${esc(c.id)}">${esc(t("Eliminar"))}</button></div></div>`).join("");$$('.rename-classroom').forEach(b=>b.addEventListener("click",()=>renameClassroom(b.dataset.id)));$$('.delete-classroom').forEach(b=>b.addEventListener("click",()=>deleteClassroom(b.dataset.id)));}
  function renderStudentAdmin(){els.studentFilter.innerHTML=`<option value="all">${esc(t("Todos los alumnos"))}</option>${app.classrooms.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("")}`;const filter=els.studentFilter.dataset.last||"all";if([...els.studentFilter.options].some(o=>o.value===filter))els.studentFilter.value=filter;const rows=app.students.filter(s=>els.studentFilter.value==="all"||s.classroom_id===els.studentFilter.value);els.studentAdminList.innerHTML=rows.map(s=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(s.name)}</strong><small>Legajo ${esc(s.record_number)} · ${esc(s.classroom_name)}</small>${s.protected?`<small class="protected-record">${esc(t("Protegido por reportes o notas"))}</small>`:""}</div><div class="row-actions"><button class="secondary-button view-student" data-id="${esc(s.id)}">${esc(t("Ver"))}</button><button class="secondary-button edit-student" data-id="${esc(s.id)}">${esc(t("Editar"))}</button><button class="danger-button delete-student" data-id="${esc(s.id)}" ${s.protected?"disabled":""}>${esc(t("Dar de baja"))}</button></div></div>`).join("");$$('.view-student').forEach(b=>b.addEventListener("click",()=>openStudentProfile(b.dataset.id)));$$('.edit-student').forEach(b=>b.addEventListener("click",()=>openStudentDialog(b.dataset.id)));$$('.delete-student').forEach(b=>b.addEventListener("click",()=>deleteStudent(b.dataset.id)));}
  function renderUserAdmin(){els.userAdminList.innerHTML=app.adminUsers.map(u=>`<div class="admin-row"><div class="admin-row-main"><strong data-i18n-skip>${esc(u.name)}</strong><small data-i18n-skip>${esc(u.email)} · ${esc(roleLabel(u.role))}</small></div><button class="secondary-button edit-user" data-id="${esc(u.id)}">${esc(t("Editar"))}</button></div>`).join("");$$('.edit-user').forEach(b=>b.addEventListener("click",()=>openUserDialog(b.dataset.id)));}
  async function renameClassroom(id){const c=app.classrooms.find(x=>x.id===id);if(!c)return;const name=prompt(t("Nuevo nombre del aula:"),c.name);if(name===null)return;try{await api(`/api/classrooms/${encodeURIComponent(id)}`,{method:"PATCH",body:{name}});toast("Aula renombrada.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(e){toast(e.message);}}
  async function deleteClassroom(id){if(!confirm(t("¿Eliminar esta aula?")))return;try{await api(`/api/classrooms/${encodeURIComponent(id)}`,{method:"DELETE"});toast("Aula eliminada.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(e){toast(e.message);}}
  function openStudentDialog(id=""){els.studentForm.reset();els.studentIdInput.value="";populateClassroomSelects();els.studentDialogTitle.textContent=t(id?"Editar alumno":"Nuevo alumno");if(id){const s=app.students.find(x=>x.id===id);if(!s)return;els.studentIdInput.value=s.id;els.studentNameInput.value=s.name;els.studentRecordInput.value=s.record_number;els.studentClassroomInput.value=s.classroom_id;els.studentDniInput.value=s.dni||"";els.studentBirthDateInput.value=s.birth_date||"";els.studentGuardianNameInput.value=s.guardian_name||"";els.studentGuardianPhoneInput.value=s.guardian_phone||"";els.studentGuardianEmailInput.value=s.guardian_email||"";els.studentEmergencyNameInput.value=s.emergency_name||"";els.studentEmergencyPhoneInput.value=s.emergency_phone||"";}els.studentDialog.showModal();}
  async function saveStudent(e){e.preventDefault();const id=els.studentIdInput.value;const body={name:els.studentNameInput.value,record_number:els.studentRecordInput.value,classroom_id:els.studentClassroomInput.value,dni:els.studentDniInput.value,birth_date:els.studentBirthDateInput.value,guardian_name:els.studentGuardianNameInput.value,guardian_phone:els.studentGuardianPhoneInput.value,guardian_email:els.studentGuardianEmailInput.value,emergency_name:els.studentEmergencyNameInput.value,emergency_phone:els.studentEmergencyPhoneInput.value};try{await api(id?`/api/students/${encodeURIComponent(id)}`:"/api/students",{method:id?"PATCH":"POST",body});els.studentDialog.close();toast(id?"Alumno actualizado.":"Alumno agregado.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(err){toast(err.message);}}
  async function deleteStudent(id){const s=app.students.find(x=>x.id===id);if(!s)return;if(s.protected)return toast("No se puede dar de baja: el alumno tiene reportes o notas del profesor.");if(!confirm(t(`¿Dar de baja a ${s.name}?`)))return;try{await api(`/api/students/${encodeURIComponent(id)}`,{method:"DELETE"});toast("Alumno dado de baja.");await renderAdmin();}catch(e){toast(e.message);}}
  async function saveSettings(e){e.preventDefault();try{const body={institution_name:els.institutionNameSetting.value,academic_year:els.academicYearSetting.value,education_level:els.educationLevelSetting.value,shifts:els.shiftsSetting.value,attendance_threshold:els.attendanceThreshold.value,absence_alert_count:els.absenceAlertCount.value,late_alert_count:els.lateAlertCount.value,default_language:els.defaultLanguageSetting.value,auto_backup_enabled:els.autoBackupEnabled.checked,backup_interval_hours:els.backupIntervalHours.value,backup_keep:els.backupKeep.value,session_hours:els.sessionHours.value,public_base_url:els.publicBaseUrl.value,google_client_id:els.googleClientId.value};if(els.googleClientSecret.value.trim())body.google_client_secret=els.googleClientSecret.value.trim();await api("/api/settings",{method:"PATCH",body});applyInstitutionBrand(body.institution_name);els.googleClientSecret.value="";toast("Configuración guardada.");await renderAdmin();await renderHome();}catch(err){toast(err.message);}}

  function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const bytes=new Uint8Array(reader.result);let binary="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));resolve(btoa(binary));};reader.readAsArrayBuffer(file);});}
  async function previewImport(){const file=els.studentImportFile.files?.[0];if(!file)return toast("Seleccioná un archivo CSV o XLSX.");try{const data_base64=await fileToBase64(file);app.importPayload={file_name:file.name,data_base64};const result=await api("/api/import/students/preview",{method:"POST",body:app.importPayload});els.importPreview.innerHTML=`<div class="import-summary"><strong>${result.valid} ${esc(t("válidos"))}</strong><span>${result.invalid} ${esc(t("con errores"))} · ${result.total} ${esc(t("filas"))}</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>${esc(t("Nombre"))}</th><th>${esc(t("Legajo"))}</th><th>${esc(t("Aula"))}</th><th>${esc(t("Resultado"))}</th></tr></thead><tbody>${(result.rows||[]).map(r=>`<tr><td>${r.row_number}</td><td data-i18n-skip>${esc(r.name)}</td><td data-i18n-skip>${esc(r.record_number)}</td><td data-i18n-skip>${esc(r.classroom)}</td><td>${r.errors.length?`<span class="danger-text">${esc(r.errors.join(", "))}</span>`:`<span class="success-text">${esc(t("Válido"))}</span>`}</td></tr>`).join("")}</tbody></table></div>`;els.commitImportButton.disabled=result.valid===0;}catch(e){toast(e.message);}}
  async function commitImport(){if(!app.importPayload)return;try{const result=await api("/api/import/students/commit",{method:"POST",body:app.importPayload});toast(`${t("Importación terminada")}: ${result.imported} ${t("alumnos")}.`);app.importPayload=null;els.commitImportButton.disabled=true;els.studentImportFile.value="";els.importPreview.innerHTML="";await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(e){toast(e.message);}}

  async function openStudentProfile(id){
    try{
      const [sd,ad,rd,nd,gd,wd,auditData]=await Promise.all([api(`/api/students/${encodeURIComponent(id)}`),api(`/api/students/${encodeURIComponent(id)}/attendance`),api(`/api/students/${encodeURIComponent(id)}/reports`),api(`/api/students/${encodeURIComponent(id)}/notes`),api(`/api/students/${encodeURIComponent(id)}/grades`),api(`/api/students/${encodeURIComponent(id)}/notices`),api(`/api/students/${encodeURIComponent(id)}/audit`)]);
      const s=sd.student;app.currentProfileStudent=s;els.profileStudentName.textContent=s.name;els.profileStudentMeta.textContent=`${t("Legajo")} #${s.record_number} · ${s.classroom_name}`;
      const summary=s.attendance_summary||{};const contacts=app.user.permissions.view_contacts?`<div class="info-card"><small>${esc(t("Madre, padre o tutor"))}</small><strong data-i18n-skip>${esc(s.guardian_name||t("No cargado"))}</strong><span data-i18n-skip>${esc(s.guardian_phone||"—")}</span><span data-i18n-skip>${esc(s.guardian_email||"—")}</span></div><div class="info-card"><small>${esc(t("Contacto de emergencia"))}</small><strong data-i18n-skip>${esc(s.emergency_name||t("No cargado"))}</strong><span data-i18n-skip>${esc(s.emergency_phone||"—")}</span></div>`:`<div class="info-card span-2"><small>${esc(t("Datos de contacto"))}</small><strong>${esc(t("Restringidos al rol de preceptor/directivo"))}</strong></div>`;
      els.profileInfoTab.innerHTML=`<div class="profile-summary-strip"><div><small>${esc(t("Asistencia"))}</small><strong>${summary.attendance_rate==null?"—":summary.attendance_rate+"%"}</strong></div><div><small>${esc(t("Ausentes"))}</small><strong>${summary.absent||0}</strong></div><div><small>${esc(t("Tarde"))}</small><strong>${summary.late||0}</strong></div><div><small>${esc(t("Justificadas"))}</small><strong>${summary.justified||0}</strong></div></div><div class="info-grid"><div class="info-card"><small>DNI</small><strong data-i18n-skip>${esc(s.dni||t("Restringido"))}</strong></div><div class="info-card"><small>${esc(t("Fecha de nacimiento"))}</small><strong>${formatDate(s.birth_date)}</strong></div>${contacts}</div>`;
      const attendance=ad.attendance||[],audit=auditData.audit||[];els.profileAttendanceTab.innerHTML=`<div class="profile-export-actions"><button class="secondary-button profile-history-export" data-format="csv">${esc(t("Historial CSV"))}</button><button class="secondary-button profile-history-export" data-format="pdf">${esc(t("Historial PDF"))}</button></div>${attendance.length?`<div class="table-wrap"><table><thead><tr><th>${esc(t("Fecha"))}</th><th>${esc(t("Estado"))}</th><th>${esc(t("Detalle"))}</th><th>${esc(t("Actualizado por"))}</th></tr></thead><tbody>${attendance.map(r=>`<tr><td>${formatDate(r.date)}</td><td><span class="status-badge ${esc(r.status)}">${esc(statusText(r.status))}</span></td><td>${esc(attendanceDetailText(r))}</td><td data-i18n-skip>${esc(r.updated_by_name)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state"><strong>${esc(t("Sin asistencia registrada."))}</strong></div>`}<div class="audit-section"><h3>${esc(t("Registro de modificaciones"))}</h3>${audit.length?`<div class="audit-list">${audit.map(a=>`<div class="audit-item"><strong>${esc(formatDateTime(a.changed_at))}</strong><span>${esc(statusText(a.old_status||""))} → ${esc(statusText(a.new_status||""))}</span><small data-i18n-skip>${esc(a.changed_by_name)}</small></div>`).join("")}</div>`:`<p class="muted">${esc(t("No hay modificaciones registradas."))}</p>`}</div>`;$$('.profile-history-export').forEach(b=>b.addEventListener("click",()=>exportStudentHistory(b.dataset.format)));
      const reports=rd.reports||[];els.profileReportsTab.innerHTML=reports.length?reports.map(r=>reportCardHtml(r,false,true)).join(""):`<div class="empty-state"><strong>${esc(t("No hay reportes visibles para tu cuenta."))}</strong></div>`;
      const notes=nd.notes||[];app.currentProfileNotes=notes;els.profileNotesTab.innerHTML=notes.length?notes.map(n=>`<article class="note-card"><p data-i18n-skip>${esc(n.note)}</p><div><small>${formatDateTime(n.updated_at||n.created_at)}</small><span class="row-actions"><button class="text-button edit-note-profile" data-id="${esc(n.id)}">${esc(t("Editar"))}</button><button class="text-button delete-note" data-id="${esc(n.id)}">${esc(t("Eliminar"))}</button></span></div></article>`).join(""):`<div class="empty-state"><strong>${esc(t("No tenés notas privadas sobre este alumno."))}</strong></div>`;
      const grades=gd.grades||[];els.profileGradesTab.innerHTML=grades.length?`<div class="table-wrap"><table><thead><tr><th>${esc(t("Evaluación"))}</th><th>${esc(t("Fecha"))}</th><th>${esc(t("Nota"))}</th><th>${esc(t("Observación"))}</th></tr></thead><tbody>${grades.map(g=>`<tr><td data-i18n-skip>${esc(g.title)}</td><td>${formatDate(g.assessment_date)}</td><td>${g.score==null?"—":`${g.score} / ${g.max_score}`}</td><td data-i18n-skip>${esc(g.comment||"—")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state"><strong>${esc(t("Sin calificaciones cargadas."))}</strong></div>`;
      const notices=wd.notices||[];els.profileNoticesTab.innerHTML=notices.length?notices.map(n=>`<article class="notice-card"><div><strong data-i18n-skip>${esc(n.reason)}</strong><span>${formatDateTime(n.created_at)} · ${esc(t(n.status==="sent"?"Enviado":"Generado"))}</span></div><p data-i18n-skip>${esc(n.message)}</p>${n.status!=="sent"?`<button class="secondary-button mark-notice-sent" data-id="${esc(n.id)}">${esc(t("Marcar como enviado"))}</button>`:""}</article>`).join(""):`<div class="empty-state"><strong>${esc(t("No hay avisos registrados."))}</strong></div>`;
      bindProfileActions();switchProfileTab("info");if(!els.studentProfileDialog.open)els.studentProfileDialog.showModal();
    }catch(e){toast(e.message);}
  }
  function bindProfileActions(){$$('.edit-note-profile').forEach(b=>b.addEventListener("click",()=>{const note=(app.currentProfileNotes||[]).find(n=>n.id===b.dataset.id);if(note)openPrivateNote(note);}));$$('.delete-note').forEach(b=>b.addEventListener("click",()=>deletePrivateNote(b.dataset.id)));$$('.mark-notice-sent').forEach(b=>b.addEventListener("click",()=>markNoticeSent(b.dataset.id)));$$('#profileReportsTab .report-followup').forEach(b=>b.addEventListener("click",()=>openFollowup(b.dataset.id)));}
  function switchProfileTab(tab){$$('.profile-tabs button').forEach(b=>b.classList.toggle("active",b.dataset.profileTab===tab));$$('.profile-tab').forEach(p=>p.classList.remove("active"));({info:els.profileInfoTab,attendance:els.profileAttendanceTab,reports:els.profileReportsTab,notes:els.profileNotesTab,grades:els.profileGradesTab,notices:els.profileNoticesTab})[tab]?.classList.add("active");}
  function openReportDialog(){const s=app.currentProfileStudent;if(!s)return;els.reportForm.reset();els.reportStudentName.textContent=s.name;els.reportStudentClass.textContent=s.classroom_name;els.reportDate.textContent=formatDate(today());els.reportDialog.showModal();}
  async function submitReport(e){e.preventDefault();const s=app.currentProfileStudent;if(!s)return;try{await api("/api/reports",{method:"POST",body:{student_id:s.id,type:els.reportType.value,description:els.reportDescription.value,priority:els.reportPriority.value}});els.reportDialog.close();toast("Reporte enviado.");await openStudentProfile(s.id);switchProfileTab("reports");}catch(err){toast(err.message);}}
  function reportCardHtml(r,review=false,profile=false){const controls=review?`<select class="status-select report-status-select" data-id="${esc(r.id)}"><option value="enviado" ${r.status==="enviado"?"selected":""}>${esc(t("Enviado"))}</option><option value="en_revision" ${r.status==="en_revision"?"selected":""}>${esc(t("En revisión"))}</option><option value="atendido" ${r.status==="atendido"?"selected":""}>${esc(t("Atendido"))}</option><option value="cerrado" ${r.status==="cerrado"?"selected":""}>${esc(t("Cerrado"))}</option></select>`:`<span class="status-badge ${esc(r.status)}">${esc(statusText(r.status))}</span>`;return `<article class="report-card"><div class="report-card-header"><div><h3 data-i18n-skip>${esc(r.student_name||app.currentProfileStudent?.name||t("Alumno"))}</h3><div class="report-meta">${esc(r.classroom_name||app.currentProfileStudent?.classroom_name||"")} · ${esc(reportTypeText(r.type))} · ${formatDateTime(r.created_at)}</div></div><span class="priority-pill ${esc(r.priority)}">${esc(priorityText(r.priority))}</span></div><p data-i18n-skip>${esc(r.description)}</p><div class="report-card-footer"><span class="report-meta">${r.reporter_name?`${esc(t("Responsable"))}: ${esc(r.reporter_name)}`:""}</span><div class="row-actions"><button class="secondary-button report-followup" data-id="${esc(r.id)}">${esc(t("Seguimiento"))}</button>${controls}</div></div></article>`;}
  async function openFollowup(id){app.currentReportId=id;try{const data=await api(`/api/reports/${encodeURIComponent(id)}/comments`);const rows=data.comments||[];els.followupList.innerHTML=rows.length?rows.map(c=>`<div class="activity-item"><strong data-i18n-skip>${esc(c.author_name)}</strong><span data-i18n-skip>${esc(c.comment)}</span><small>${formatDateTime(c.created_at)}</small></div>`).join(""):`<div class="empty-state"><strong>${esc(t("Sin comentarios de seguimiento."))}</strong></div>`;els.followupComment.value="";els.followupDialog.showModal();}catch(e){toast(e.message);}}
  async function submitFollowup(e){e.preventDefault();if(!app.currentReportId)return;try{await api(`/api/reports/${encodeURIComponent(app.currentReportId)}/comments`,{method:"POST",body:{comment:els.followupComment.value}});toast("Seguimiento agregado.");await openFollowup(app.currentReportId);}catch(err){toast(err.message);}}
  function openPrivateNote(note=null){
    els.noteForm.reset();app.editingNoteId=note?.id||null;els.privateNoteText.value=note?.note||"";
    if(els.noteDialogTitle)els.noteDialogTitle.textContent=t(note?"Editar nota privada":"Nota privada docente");
    els.noteDialog.showModal();
  }
  async function savePrivateNote(e){
    e.preventDefault();
    try{
      if(app.editingNoteId){await api(`/api/notes/${encodeURIComponent(app.editingNoteId)}`,{method:"PATCH",body:{note:els.privateNoteText.value}});toast("Nota privada actualizada.");}
      else{const s=app.currentProfileStudent;if(!s)return;await api("/api/notes",{method:"POST",body:{student_id:s.id,note:els.privateNoteText.value}});toast("Nota privada guardada.");}
      els.noteDialog.close();app.editingNoteId=null;
      if(els.studentProfileDialog?.open&&app.currentProfileStudent){const sid=app.currentProfileStudent.id;await openStudentProfile(sid);switchProfileTab("notes");}
      if(document.querySelector('#notesView.active'))await renderPrivateNotes();
    }catch(err){toast(err.message);}
  }
  async function deletePrivateNote(id,{fromProfile=true}={}){
    if(!confirm(t("¿Eliminar esta nota privada?")))return;
    try{await api(`/api/notes/${encodeURIComponent(id)}`,{method:"DELETE"});toast("Nota privada eliminada.");if(fromProfile&&app.currentProfileStudent){await openStudentProfile(app.currentProfileStudent.id);switchProfileTab("notes");}if(document.querySelector('#notesView.active'))await renderPrivateNotes();}catch(e){toast(e.message);}
  }
  async function renderPrivateNotes(){
    if(!app.user)return;
    try{
      const q=els.privateNotesSearch?.value.trim()||"";const cid=els.privateNotesClassroom?.value||"all";
      const data=await api(`/api/notes?q=${encodeURIComponent(q)}&classroom_id=${encodeURIComponent(cid)}`);
      const rows=data.notes||[];app.privateNotes=rows;
      if(els.privateNotesClassroom){const previous=els.privateNotesClassroom.value||"all";const known=new Map((app.classrooms||[]).map(c=>[c.id,c.name]));rows.forEach(n=>known.set(n.classroom_id,n.classroom_name));els.privateNotesClassroom.innerHTML=`<option value="all">${esc(t("Todas mis aulas"))}</option>`+[...known.entries()].sort((a,b)=>a[1].localeCompare(b[1],I18N?.locale?.()||"es")).map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join("");if([...els.privateNotesClassroom.options].some(o=>o.value===previous))els.privateNotesClassroom.value=previous;}
      els.privateNotesList.innerHTML=rows.map(n=>`<article class="private-note-row"><div class="private-note-heading"><div><strong data-i18n-skip>${esc(n.student_name)}</strong><span data-i18n-skip>${esc(n.classroom_name)} · ${esc(t("Legajo"))} ${esc(n.record_number)}</span></div><small>${formatDateTime(n.updated_at||n.created_at)}</small></div><p data-i18n-skip>${esc(n.note)}</p><div class="row-actions"><button class="secondary-button note-open-student" data-student="${esc(n.student_id)}">${esc(t("Ver alumno"))}</button><button class="secondary-button note-edit-global" data-id="${esc(n.id)}">${esc(t("Editar"))}</button><button class="danger-button note-delete-global" data-id="${esc(n.id)}">${esc(t("Eliminar"))}</button></div></article>`).join("");
      els.noPrivateNotes.classList.toggle("hidden",rows.length>0);
      $$('.note-open-student').forEach(b=>b.addEventListener("click",()=>openStudentProfile(b.dataset.student)));
      $$('.note-edit-global').forEach(b=>b.addEventListener("click",()=>{const note=app.privateNotes.find(n=>n.id===b.dataset.id);if(note)openPrivateNote(note);}));
      $$('.note-delete-global').forEach(b=>b.addEventListener("click",()=>deletePrivateNote(b.dataset.id,{fromProfile:false})));
    }catch(e){toast(e.message);}
  }
  function openNotice(){const s=app.currentProfileStudent;if(!s)return;els.noticeForm.reset();els.noticeReason.value=t("Seguimiento de asistencia");els.noticeMessage.value=`${t("Familia de")} ${s.name}:\n\n`;els.noticeSendGmail.checked=false;els.noticeSendGmail.disabled=!app.google?.gmail_enabled;els.noticeSendGmail.closest("label")?.classList.toggle("muted",!app.google?.gmail_enabled);els.noticeDialog.showModal();}
  async function saveNotice(e){e.preventDefault();const s=app.currentProfileStudent;if(!s)return;const message=els.noticeMessage.value;try{const created=await api("/api/notices",{method:"POST",body:{student_id:s.id,reason:els.noticeReason.value,message,mark_sent:els.noticeMarkSent.checked}});if(els.noticeSendGmail.checked&&created.id){await api(`/api/notices/${encodeURIComponent(created.id)}/send-gmail`,{method:"POST",body:{}});toast("Aviso guardado y enviado por Gmail.");}else{navigator.clipboard?.writeText(message).catch(()=>{});toast("Aviso guardado y copiado.");}els.noticeDialog.close();await openStudentProfile(s.id);switchProfileTab("notices");}catch(err){toast(err.message);}}
  async function markNoticeSent(id){try{await api(`/api/notices/${encodeURIComponent(id)}/sent`,{method:"PATCH",body:{}});await openStudentProfile(app.currentProfileStudent.id);switchProfileTab("notices");}catch(e){toast(e.message);}}

  async function saveProfile(e){e.preventDefault();try{const data=await api("/api/profile",{method:"PATCH",body:{name:els.profileNameInput.value,email:els.profileEmailInput.value,preferred_language:els.profileLanguageInput.value,avatar_url:els.profileAvatarInput.value,use_google_picture:els.profileUseGooglePicture.checked}});app.user=data.user;if(app.user.preferred_language)I18N?.setLanguage?.(app.user.preferred_language);updateAuthUI();toast("Perfil actualizado.");}catch(err){toast(err.message);}}
  function renderGoogleStatus(){const g=app.google||{};if(!els.googleStatusTitle)return;els.googleStatusTitle.textContent=t(g.connected?`Conectada: ${g.email||"Google"}`:"No conectada");const details=[];if(!g.configured)details.push(t("La institución debe configurar OAuth antes de conectar una cuenta."));else if(!g.storage_available)details.push(t("El almacenamiento seguro de tokens no está disponible en este sistema."));else if(g.connected)details.push(g.gmail_enabled?t("Gmail habilitado únicamente para enviar avisos."):t("Perfil y correo conectados. Gmail no está habilitado."));else details.push(t("OAuth está configurado y listo para conectar."));els.googleStatusDetail.textContent=details.join(" ");els.connectGoogleButton.disabled=!g.configured||!g.storage_available;els.enableGmailButton.disabled=!g.connected||g.gmail_enabled||!g.storage_available;if(els.testGmailButton)els.testGmailButton.disabled=!g.connected||!g.gmail_enabled||!g.storage_available;els.disconnectGoogleButton.disabled=!g.connected;}
  async function refreshGoogleStatus(){if(!app.user)return;try{app.google=await api("/api/google/status");renderGoogleStatus();}catch(e){app.google=null;renderGoogleStatus();}}
  async function connectGoogle(mode="profile"){try{const data=await api(`/api/google/auth-url?mode=${encodeURIComponent(mode)}`);const w=window.open(data.url,"presencialidad-google","width=620,height=760");if(!w)location.href=data.url;}catch(e){toast(e.message);}}
  async function testGmail(){try{const result=await api("/api/google/test-gmail",{method:"POST",body:{}});toast(`${t("Correo de prueba enviado a")} ${result.to||app.google?.email||"Gmail"}.`);}catch(e){toast(e.message);}}
  async function disconnectGoogle(){if(!confirm(t("¿Desconectar la cuenta Google?")))return;try{await api("/api/google",{method:"DELETE"});app.google=null;await refreshGoogleStatus();toast("Cuenta Google desconectada.");}catch(e){toast(e.message);}}
  async function loadSessions(){try{const data=await api("/api/auth/sessions");const rows=data.sessions||[];els.sessionList.innerHTML=rows.map(s=>`<div class="admin-row"><div class="admin-row-main"><strong>${esc(s.current?t("Sesión actual"):t("Otra sesión"))}</strong><small>${formatDateTime(s.last_seen)} · ${esc(s.user_agent||t("Navegador desconocido"))}</small></div>${s.current?"":`<button class="danger-button revoke-session" data-id="${esc(s.id)}">${esc(t("Cerrar"))}</button>`}</div>`).join("");$$('.revoke-session').forEach(b=>b.addEventListener("click",()=>revokeSession(b.dataset.id)));}catch(e){toast(e.message);}}
  async function revokeSession(id){try{await api(`/api/auth/sessions/${encodeURIComponent(id)}`,{method:"DELETE"});await loadSessions();toast("Sesión cerrada.");}catch(e){toast(e.message);}}
  async function revokeOtherSessions(){try{const r=await api("/api/auth/revoke-others",{method:"POST",body:{}});toast(`${r.deleted||0} ${t("sesiones cerradas")}.`);await loadSessions();}catch(e){toast(e.message);}}
  async function renderAccountData(){if(!app.user)return;updateAuthUI();refreshGoogleStatus();loadSessions();try{const [mine,activity]=await Promise.all([api("/api/reports/mine"),api("/api/activity?scope=mine&limit=50")]);const reports=mine.reports||[];els.myReportsList.innerHTML=reports.map(r=>reportCardHtml(r)).join("");els.noMyReports.classList.toggle("hidden",reports.length>0);els.activityList.innerHTML=(activity.activity||[]).map(a=>`<div class="activity-item"><strong>${formatDateTime(a.created_at)}</strong><span>${esc(t(a.details))}</span></div>`).join("")||`<div class="empty-state"><strong>${esc(t("Sin actividad registrada."))}</strong></div>`;$$('#myReportsList .report-followup').forEach(b=>b.addEventListener("click",()=>openFollowup(b.dataset.id)));if(app.user.permissions.review_reports){const all=await api("/api/reports");els.reviewReportsList.innerHTML=(all.reports||[]).map(r=>reportCardHtml(r,true)).join("")||`<div class="empty-state"><strong>${esc(t("No hay reportes."))}</strong></div>`;$$('#reviewReportsList .report-status-select').forEach(sel=>sel.addEventListener("change",()=>updateReportStatus(sel.dataset.id,sel.value)));$$('#reviewReportsList .report-followup').forEach(b=>b.addEventListener("click",()=>openFollowup(b.dataset.id)));}}catch(e){toast(e.message);}}
  async function updateReportStatus(id,status){try{await api(`/api/reports/${encodeURIComponent(id)}/status`,{method:"PATCH",body:{status}});toast("Estado actualizado.");await renderAccountData();}catch(e){toast(e.message);}}
  function switchAccountTab(tab){$$('#accountTabs button').forEach(b=>b.classList.toggle("active",b.dataset.accountTab===tab));$$('.account-tab').forEach(p=>p.classList.remove("active"));const id=tab==="profile"?"profileEditTab":`${tab}Tab`;document.getElementById(id)?.classList.add("active");if(tab==="security")loadSessions();if(tab==="google")refreshGoogleStatus();}

  async function login(e){e.preventDefault();try{const data=await api("/api/auth/login",{method:"POST",body:{email:els.loginEmail.value,password:els.loginPassword.value}});app.user=data.user;app.csrf=data.csrf_token||"";app.google=data.google||null;els.loginForm.reset();if(app.user?.preferred_language)I18N?.setLanguage?.(app.user.preferred_language);await loadClassrooms();updateAuthUI();renderClassroomCards();toast(`Sesión iniciada como ${roleLabel(app.user.role)}.`);switchView("homeView");syncPendingDrafts();}catch(err){if(err.data?.setup_required){await checkSetup();return;}toast(err.message);}}
  async function logout(){if(app.attendanceDirty)persistLocalDraft();try{await api("/api/auth/logout",{method:"POST",body:{}});}catch(_){}app.user=null;app.csrf="";app.google=null;app.classrooms=[];closeClassroom();updateAuthUI();switchView("accountView");toast("Sesión cerrada.");}
  async function changePassword(e){e.preventDefault();if(els.newPassword.value!==els.repeatPassword.value)return toast("Las contraseñas nuevas no coinciden.");try{await api("/api/auth/change-password",{method:"POST",body:{current_password:els.currentPassword.value,new_password:els.newPassword.value}});els.changePasswordForm.reset();toast("Contraseña actualizada.");}catch(err){toast(err.message);}}

  function openUserDialog(id=""){els.userForm.reset();els.userIdInput.value="";els.userDialogTitle.textContent=t(id?"Editar cuenta":"Nueva cuenta");els.initialPasswordField.classList.toggle("hidden",!!id);els.userPasswordInput.required=!id;els.resetUserPasswordButton.classList.toggle("hidden",!id);els.userActiveLabel.classList.toggle("hidden",!id);els.userActiveInput.checked=true;els.userClassroomChecks.innerHTML=app.classrooms.map(c=>`<label><input type="checkbox" value="${esc(c.id)}"> ${esc(c.name)}</label>`).join("");if(id){const u=app.adminUsers.find(x=>x.id===id);if(!u)return;els.userIdInput.value=u.id;els.userNameInput.value=u.name;els.userEmailInput.value=u.email;els.userRoleInput.value=u.role;els.userInstitutionInput.value=u.institution||"";els.userActiveInput.checked=!!u.active;const ids=new Set((u.classrooms||[]).map(c=>c.id));$$('#userClassroomChecks input').forEach(i=>i.checked=ids.has(i.value));}els.userDialog.showModal();}
  async function saveUser(e){e.preventDefault();const id=els.userIdInput.value,classroom_ids=$$('#userClassroomChecks input:checked').map(i=>i.value);const body={name:els.userNameInput.value,email:els.userEmailInput.value,role:els.userRoleInput.value,institution:els.userInstitutionInput.value,classroom_ids};if(id)body.active=els.userActiveInput.checked;else body.password=els.userPasswordInput.value;try{await api(id?`/api/admin/users/${encodeURIComponent(id)}`:"/api/admin/users",{method:id?"PATCH":"POST",body});els.userDialog.close();toast(id?"Cuenta actualizada.":"Cuenta creada.");await renderAdmin();}catch(err){toast(err.message);}}
  async function resetUserPassword(){const id=els.userIdInput.value;if(!id)return;const password=prompt(t("Nueva contraseña temporal (mínimo 10 caracteres):"));if(password===null)return;try{await api(`/api/admin/users/${encodeURIComponent(id)}/reset-password`,{method:"PATCH",body:{password}});toast("Contraseña restablecida y sesiones anteriores cerradas.");}catch(e){toast(e.message);}}

  async function refreshSystem(){try{const data=await api("/api/status");els.appVersionValue.textContent=data.version||VERSION;els.backendStatusValue.textContent=t("Conectado");els.backendModeValue.textContent=`Python ${data.python_version} · ${data.platform}`;els.uptimeValue.textContent=formatDuration(data.uptime_seconds);els.requestsValue.textContent=data.request_count;els.dbSizeValue.textContent=formatBytes(data.database_bytes);els.dbNameValue.textContent=data.database;els.dbIntegrityValue.textContent=data.integrity||"—";els.dataDirValue.textContent=data.data_dir||"—";const s=data.stats||{};els.statUsers.textContent=s.users??"—";els.statClassrooms.textContent=s.classrooms??"—";els.statStudents.textContent=s.students??"—";els.statAttendance.textContent=s.attendance??"—";els.statReports.textContent=s.reports??"—";els.statNotes.textContent=s.notes??"—";els.statAssessments.textContent=s.assessments??"—";els.statSchedule.textContent=s.schedule??"—";}catch(_){els.backendStatusValue.textContent=t("Desconectado");els.backendModeValue.textContent=t("Abrí la app mediante server.py");}}
  async function showSpecs(){try{const s=await api("/api/specs");const rows=[[t("Nombre"),s.name],[t("Versión"),s.version],[t("Frontend"),s.frontend.join(", ")],[t("Backend"),s.backend],[t("Base de datos"),s.database],[t("Autenticación"),s.authentication],[t("Roles"),(s.roles||[]).map(t).join(", ")],[t("Idiomas"),(s.languages||[]).join(", ")],[t("Asistencia"),(s.attendance||[]).map(t).join(" · ")],[t("Módulos"),(s.modules||[]).map(t).join(" · ")]];els.specsContent.innerHTML=rows.map(([k,v])=>`<div class="spec-row"><span>${esc(k)}</span><strong data-i18n-skip>${esc(v)}</strong></div>`).join("");els.specsDialog.showModal();}catch(e){toast(e.message);}}
  async function migrateLegacy(){let state;try{state=JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)||"null");}catch(_){state=null;}if(!state)return toast("No se encontraron datos locales de v3 en este navegador.");if(!confirm(t("¿Importar los datos locales de v3 a la base SQLite? Los datos actuales no se borrarán.")))return;try{const result=await api("/api/migrate/local",{method:"POST",body:{state}});const i=result.imported||{};toast(`${t("Importación terminada")}: ${i.classrooms||0} ${t("aulas")}, ${i.students||0} ${t("alumnos")}.`);await loadClassrooms();renderClassroomCards();await refreshSystem();}catch(e){toast(e.message);}}
  function openClearHistory(){els.confirmClearInput.value="";els.confirmClearAction.disabled=true;els.confirmClearDialog.showModal();}
  async function clearHistory(){if(els.confirmClearInput.value!=="BORRAR")return;try{const result=await api("/api/attendance/history",{method:"DELETE"});els.confirmClearDialog.close();toast(`${t("Historial borrado")}: ${result.deleted} ${t("registros")}.`);await renderHistory();await refreshSystem();}catch(e){toast(e.message);}}

  async function handleSearchInput(){clearTimeout(app.searchTimer);const q=els.globalSearchInput.value.trim();if(q.length<2){els.globalSearchResults.classList.add("hidden");els.globalSearchResults.innerHTML="";return;}app.searchTimer=setTimeout(async()=>{try{const data=await api(`/api/search?q=${encodeURIComponent(q)}`);const rows=data.results||[];els.globalSearchResults.innerHTML=rows.length?rows.map(r=>`<button class="search-result" data-id="${esc(r.id)}"><strong data-i18n-skip>${esc(r.name)}</strong><span>Legajo ${esc(r.record_number)} · ${esc(r.classroom_name)}</span></button>`).join(""):`<div class="search-empty">${esc(t("Sin resultados"))}</div>`;els.globalSearchResults.classList.remove("hidden");$$('.search-result').forEach(b=>b.addEventListener("click",()=>{els.globalSearchResults.classList.add("hidden");els.globalSearchInput.value="";openStudentProfile(b.dataset.id);}));}catch(_){els.globalSearchResults.classList.add("hidden");}},220);}

  async function exportAttendance(format){const month=els.reportMonth.value||monthNow(),cid=els.reportClassroom.value||"all";try{await downloadApi(`/api/export/attendance.${format}?month=${encodeURIComponent(month)}&classroom_id=${encodeURIComponent(cid)}`);}catch(e){toast(e.message);}}
  async function exportStudents(format){const cid=els.reportClassroom.value||"all";try{await downloadApi(`/api/export/students.${format}?classroom_id=${encodeURIComponent(cid)}`);}catch(e){toast(e.message);}}
  async function exportReports(format){try{await downloadApi(`/api/export/reports.${format}`);}catch(e){toast(e.message);}}
  async function exportStudentHistory(format){const s=app.currentProfileStudent;if(!s)return;try{await downloadApi(`/api/export/student-history.${format}?student_id=${encodeURIComponent(s.id)}`);}catch(e){toast(e.message);}}

  async function handleLanguageChange(){updateAuthUI();renderClassroomCards();if(app.user){const active=document.querySelector('.view.active')?.id;switchView(active||"homeView");if(app.selectedClassroomId)renderAttendance();}I18N?.refresh?.();}

  function bindEvents(){
    els.navButtons.forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$$('[data-go-view]').forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.goView)));$$('[data-focus-search]').forEach(b=>b.addEventListener("click",()=>{els.globalSearchInput.focus();}));
    els.globalSearchInput.addEventListener("input",handleSearchInput);document.addEventListener("click",e=>{if(!e.target.closest('.global-search-wrap'))els.globalSearchResults.classList.add("hidden");});
    els.backToClassrooms.addEventListener("click",closeClassroom);els.markAllPresent.addEventListener("click",markAllPresent);els.saveAttendance.addEventListener("click",saveAttendance);els.attendanceDate.addEventListener("change",()=>{if(app.selectedClassroomId)openClassroom(app.selectedClassroomId);});
    els.historyDate.addEventListener("change",renderHistory);els.historyClassroom.addEventListener("change",renderHistory);els.clearHistoryButton.addEventListener("click",openClearHistory);els.exportAttendanceCsv.addEventListener("click",()=>exportAttendance("csv"));els.exportAttendancePdf.addEventListener("click",()=>exportAttendance("pdf"));els.exportStudentsCsv.addEventListener("click",()=>exportStudents("csv"));els.exportStudentsPdf.addEventListener("click",()=>exportStudents("pdf"));els.exportReportsCsv.addEventListener("click",()=>exportReports("csv"));els.exportReportsPdf.addEventListener("click",()=>exportReports("pdf"));
    els.privateNotesSearch?.addEventListener("input",()=>{clearTimeout(app.searchTimer);app.searchTimer=setTimeout(renderPrivateNotes,220);});els.privateNotesClassroom?.addEventListener("change",renderPrivateNotes);els.refreshPrivateNotesButton?.addEventListener("click",renderPrivateNotes);
    els.gradesClassroom.addEventListener("change",loadAssessments);els.newAssessmentButton.addEventListener("click",openAssessmentDialog);els.assessmentForm.addEventListener("submit",createAssessment);els.gradesForm.addEventListener("submit",saveGrades);
    els.scheduleForm.addEventListener("submit",createSchedule);
    els.classroomForm.addEventListener("submit",async e=>{e.preventDefault();try{await api("/api/classrooms",{method:"POST",body:{name:els.classroomNameInput.value}});els.classroomForm.reset();toast("Aula creada.");await loadClassrooms();await renderAdmin();renderClassroomCards();}catch(err){toast(err.message);}});els.studentFilter.addEventListener("change",()=>{els.studentFilter.dataset.last=els.studentFilter.value;renderStudentAdmin();});els.newStudentButton.addEventListener("click",()=>openStudentDialog());els.studentForm.addEventListener("submit",saveStudent);els.newUserButton.addEventListener("click",()=>openUserDialog());els.userForm.addEventListener("submit",saveUser);els.resetUserPasswordButton.addEventListener("click",resetUserPassword);els.previewImportButton.addEventListener("click",previewImport);els.commitImportButton.addEventListener("click",commitImport);els.settingsForm.addEventListener("submit",saveSettings);els.createBackupButton.addEventListener("click",createBackup);
    els.setupForm.addEventListener("submit",completeSetup);els.loginForm.addEventListener("submit",login);els.logoutButton.addEventListener("click",logout);els.profileForm.addEventListener("submit",saveProfile);els.changePasswordForm.addEventListener("submit",changePassword);els.revokeOtherSessions.addEventListener("click",revokeOtherSessions);els.connectGoogleButton.addEventListener("click",()=>connectGoogle("profile"));els.enableGmailButton.addEventListener("click",()=>connectGoogle("gmail"));els.testGmailButton?.addEventListener("click",testGmail);els.disconnectGoogleButton.addEventListener("click",disconnectGoogle);els.forgotPasswordButton.addEventListener("click",()=>alert(t("Por seguridad, solicitá al directivo o administrador de la institución el restablecimiento de tu contraseña. La aplicación no envía correos por sí sola en esta versión.")));$$('#accountTabs button').forEach(b=>b.addEventListener("click",()=>switchAccountTab(b.dataset.accountTab)));
    $$('.profile-tabs button').forEach(b=>b.addEventListener("click",()=>switchProfileTab(b.dataset.profileTab)));els.reportStudentButton.addEventListener("click",openReportDialog);els.reportForm.addEventListener("submit",submitReport);els.privateNoteButton.addEventListener("click",openPrivateNote);els.noteForm.addEventListener("submit",savePrivateNote);els.familyNoticeButton.addEventListener("click",openNotice);els.noticeForm.addEventListener("submit",saveNotice);els.followupForm.addEventListener("submit",submitFollowup);
    $$('[data-theme-choice]').forEach(b=>b.addEventListener("click",()=>saveAppearance({theme:b.dataset.themeChoice})));$$('.color-choice').forEach(b=>b.addEventListener("click",()=>saveAppearance({accent:b.dataset.accent})));
    els.refreshSystemButton.addEventListener("click",refreshSystem);els.specsHelpButton.addEventListener("click",showSpecs);els.migrateLocalButton.addEventListener("click",migrateLegacy);els.confirmClearInput.addEventListener("input",()=>els.confirmClearAction.disabled=els.confirmClearInput.value!=="BORRAR");els.confirmClearAction.addEventListener("click",clearHistory);$$('[data-close]').forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.close)?.close()));window.addEventListener("presencialidad-language-change",handleLanguageChange);window.addEventListener("message",e=>{if(e.origin===location.origin&&e.data?.type==="presencialidad-google-connected"){refreshGoogleStatus();api("/api/auth/me").then(d=>{app.user=d.user;app.csrf=d.csrf_token||app.csrf;app.google=d.google||app.google;updateAuthUI();});}});window.addEventListener("online",()=>{setConnection(true);syncPendingDrafts();});window.addEventListener("offline",()=>setConnection(false));window.addEventListener("beforeunload",e=>{if(app.attendanceDirty){persistLocalDraft();e.preventDefault();e.returnValue="";}});
  }

  async function init(){applyAppearance();bindEvents();bindRestrictedInputs();els.attendanceDate.value=today();els.historyDate.value=today();els.reportMonth.value=monthNow();els.scheduleDate.value=today();els.appVersionValue.textContent=VERSION;setInterval(autosaveAttendanceDraft,AUTOSAVE_MS);if(location.protocol==="file:")els.backendBanner.classList.remove("hidden");await refreshSystem();await checkBackendAndSession();I18N?.refresh?.();}
  init();
})();
